name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/terraform-provider-ansible_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Zip
        run: |
          cd dist
          zip terraform-provider-ansible_${{ matrix.goos }}_${{ matrix.goarch }}.zip terraform-provider-ansible_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-ansible-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*.zip
